replicaCount: 1

image:
  repository: ghcr.io/pierinho13/github-platform-operator
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

leaderElection:
  enabled: true

metrics:
  enabled: true
  secure: true
  port: 8443
  service:
    type: ClusterIP
    annotations: {}
  serviceMonitor:
    enabled: false
    namespace: ""
    additionalLabels: {}
    annotations: {}
    interval: 30s
    scrapeTimeout: 10s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
  readerBinding:
    enabled: false
    subjects: []

networkPolicy:
  enabled: false
  namespaceSelectorLabels:
    metrics: enabled

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

extraArgs: []

nodeSelector: {}
tolerations: []
affinity: {}

terminationGracePeriodSeconds: 10
revisionHistoryLimit: 3
