apiVersion: github.k8sready.com/v1alpha1
kind: GitHubRepository
metadata:
  name: test-repository
  namespace: default
spec:
  providerConfigRef: default
  name: test-repository
  visibility: private
