apiVersion: github.k8sready.com/v1alpha1
kind: GitHubActionsSecret
metadata:
  name: organization-npm-token
  namespace: default
spec:
  target:
    organization:
      providerConfigRef: default
      visibility: selected
      selectedRepositoryRefs:
        - name: example-repository
  name: NPM_TOKEN
  valueFrom:
    secretKeyRef:
      name: organization-actions-values
      key: npm-token
  deletionPolicy: Orphan
