apiVersion: github.k8sready.com/v1alpha1
kind: GitHubActionsSecret
metadata:
  name: production-database-password
  namespace: default
spec:
  target:
    environmentRef:
      name: example-repository-production
  name: DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: production-actions-values
      key: database-password
  deletionPolicy: Orphan
