apiVersion: github.k8sready.com/v1alpha1
kind: GitHubRepository
metadata:
  labels:
    app.kubernetes.io/name: github-platform-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubrepository-sample
spec:
  # TODO(user): Add fields here
