apiVersion: github.k8sready.com/v1alpha1
kind: GitHubActionsSecret
metadata:
  name: example-repository-docker-token
  namespace: default
spec:
  target:
    repositoryRef:
      name: example-repository
  name: DOCKER_TOKEN
  valueFrom:
    secretKeyRef:
      name: github-actions-values
      key: docker-token
  deletionPolicy: Orphan
