## Append samples of your project ##
resources:
- github_v1alpha1_githubproviderconfig.yaml
- github_v1alpha1_githubrepository.yaml
- github_v1alpha1_githubrepositoryteamaccess.yaml
- github_v1alpha1_githubrepositorycollaborator.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
