//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsValueSource) DeepCopyInto(out *ActionsValueSource) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsValueSource.
func (in *ActionsValueSource) DeepCopy() *ActionsValueSource {
	if in == nil {
		return nil
	}
	out := new(ActionsValueSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsSecret) DeepCopyInto(out *GitHubActionsSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsSecret.
func (in *GitHubActionsSecret) DeepCopy() *GitHubActionsSecret {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubActionsSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsSecretList) DeepCopyInto(out *GitHubActionsSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubActionsSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsSecretList.
func (in *GitHubActionsSecretList) DeepCopy() *GitHubActionsSecretList {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubActionsSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsSecretSpec) DeepCopyInto(out *GitHubActionsSecretSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	out.ValueFrom = in.ValueFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsSecretSpec.
func (in *GitHubActionsSecretSpec) DeepCopy() *GitHubActionsSecretSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsSecretStatus) DeepCopyInto(out *GitHubActionsSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsSecretStatus.
func (in *GitHubActionsSecretStatus) DeepCopy() *GitHubActionsSecretStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsTarget) DeepCopyInto(out *GitHubActionsTarget) {
	*out = *in
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(GitHubRepositoryReference)
		**out = **in
	}
	if in.EnvironmentRef != nil {
		in, out := &in.EnvironmentRef, &out.EnvironmentRef
		*out = new(GitHubEnvironmentReference)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(GitHubOrganizationActionsTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsTarget.
func (in *GitHubActionsTarget) DeepCopy() *GitHubActionsTarget {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsVariable) DeepCopyInto(out *GitHubActionsVariable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsVariable.
func (in *GitHubActionsVariable) DeepCopy() *GitHubActionsVariable {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubActionsVariable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsVariableList) DeepCopyInto(out *GitHubActionsVariableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubActionsVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsVariableList.
func (in *GitHubActionsVariableList) DeepCopy() *GitHubActionsVariableList {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsVariableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubActionsVariableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsVariableSpec) DeepCopyInto(out *GitHubActionsVariableSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	out.ValueFrom = in.ValueFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsVariableSpec.
func (in *GitHubActionsVariableSpec) DeepCopy() *GitHubActionsVariableSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsVariableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubActionsVariableStatus) DeepCopyInto(out *GitHubActionsVariableStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubActionsVariableStatus.
func (in *GitHubActionsVariableStatus) DeepCopy() *GitHubActionsVariableStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubActionsVariableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppCredentials) DeepCopyInto(out *GitHubAppCredentials) {
	*out = *in
	out.PrivateKeySecretRef = in.PrivateKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppCredentials.
func (in *GitHubAppCredentials) DeepCopy() *GitHubAppCredentials {
	if in == nil {
		return nil
	}
	out := new(GitHubAppCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubEnvironment) DeepCopyInto(out *GitHubEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubEnvironment.
func (in *GitHubEnvironment) DeepCopy() *GitHubEnvironment {
	if in == nil {
		return nil
	}
	out := new(GitHubEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubEnvironmentList) DeepCopyInto(out *GitHubEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubEnvironmentList.
func (in *GitHubEnvironmentList) DeepCopy() *GitHubEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(GitHubEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubEnvironmentReference) DeepCopyInto(out *GitHubEnvironmentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubEnvironmentReference.
func (in *GitHubEnvironmentReference) DeepCopy() *GitHubEnvironmentReference {
	if in == nil {
		return nil
	}
	out := new(GitHubEnvironmentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubEnvironmentSpec) DeepCopyInto(out *GitHubEnvironmentSpec) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubEnvironmentSpec.
func (in *GitHubEnvironmentSpec) DeepCopy() *GitHubEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubEnvironmentStatus) DeepCopyInto(out *GitHubEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubEnvironmentStatus.
func (in *GitHubEnvironmentStatus) DeepCopy() *GitHubEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubOrganizationActionsTarget) DeepCopyInto(out *GitHubOrganizationActionsTarget) {
	*out = *in
	if in.SelectedRepositoryRefs != nil {
		in, out := &in.SelectedRepositoryRefs, &out.SelectedRepositoryRefs
		*out = make([]GitHubRepositoryReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubOrganizationActionsTarget.
func (in *GitHubOrganizationActionsTarget) DeepCopy() *GitHubOrganizationActionsTarget {
	if in == nil {
		return nil
	}
	out := new(GitHubOrganizationActionsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubOrganizationMember) DeepCopyInto(out *GitHubOrganizationMember) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubOrganizationMember.
func (in *GitHubOrganizationMember) DeepCopy() *GitHubOrganizationMember {
	if in == nil {
		return nil
	}
	out := new(GitHubOrganizationMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubOrganizationMember) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubOrganizationMemberList) DeepCopyInto(out *GitHubOrganizationMemberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubOrganizationMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubOrganizationMemberList.
func (in *GitHubOrganizationMemberList) DeepCopy() *GitHubOrganizationMemberList {
	if in == nil {
		return nil
	}
	out := new(GitHubOrganizationMemberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubOrganizationMemberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubOrganizationMemberSpec) DeepCopyInto(out *GitHubOrganizationMemberSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubOrganizationMemberSpec.
func (in *GitHubOrganizationMemberSpec) DeepCopy() *GitHubOrganizationMemberSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubOrganizationMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubOrganizationMemberStatus) DeepCopyInto(out *GitHubOrganizationMemberStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubOrganizationMemberStatus.
func (in *GitHubOrganizationMemberStatus) DeepCopy() *GitHubOrganizationMemberStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubOrganizationMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubProviderConfig) DeepCopyInto(out *GitHubProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubProviderConfig.
func (in *GitHubProviderConfig) DeepCopy() *GitHubProviderConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubProviderConfigList) DeepCopyInto(out *GitHubProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubProviderConfigList.
func (in *GitHubProviderConfigList) DeepCopy() *GitHubProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(GitHubProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubProviderConfigSpec) DeepCopyInto(out *GitHubProviderConfigSpec) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubProviderConfigSpec.
func (in *GitHubProviderConfigSpec) DeepCopy() *GitHubProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubProviderConfigStatus) DeepCopyInto(out *GitHubProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubProviderConfigStatus.
func (in *GitHubProviderConfigStatus) DeepCopy() *GitHubProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubProviderCredentials) DeepCopyInto(out *GitHubProviderCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(NamespacedSecretKeyReference)
		**out = **in
	}
	if in.GitHubApp != nil {
		in, out := &in.GitHubApp, &out.GitHubApp
		*out = new(GitHubAppCredentials)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubProviderCredentials.
func (in *GitHubProviderCredentials) DeepCopy() *GitHubProviderCredentials {
	if in == nil {
		return nil
	}
	out := new(GitHubProviderCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepository) DeepCopyInto(out *GitHubRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepository.
func (in *GitHubRepository) DeepCopy() *GitHubRepository {
	if in == nil {
		return nil
	}
	out := new(GitHubRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryCollaborator) DeepCopyInto(out *GitHubRepositoryCollaborator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryCollaborator.
func (in *GitHubRepositoryCollaborator) DeepCopy() *GitHubRepositoryCollaborator {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryCollaborator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryCollaborator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryCollaboratorList) DeepCopyInto(out *GitHubRepositoryCollaboratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubRepositoryCollaborator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryCollaboratorList.
func (in *GitHubRepositoryCollaboratorList) DeepCopy() *GitHubRepositoryCollaboratorList {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryCollaboratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryCollaboratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryCollaboratorSpec) DeepCopyInto(out *GitHubRepositoryCollaboratorSpec) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryCollaboratorSpec.
func (in *GitHubRepositoryCollaboratorSpec) DeepCopy() *GitHubRepositoryCollaboratorSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryCollaboratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryCollaboratorStatus) DeepCopyInto(out *GitHubRepositoryCollaboratorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryCollaboratorStatus.
func (in *GitHubRepositoryCollaboratorStatus) DeepCopy() *GitHubRepositoryCollaboratorStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryCollaboratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryList) DeepCopyInto(out *GitHubRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryList.
func (in *GitHubRepositoryList) DeepCopy() *GitHubRepositoryList {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryReference) DeepCopyInto(out *GitHubRepositoryReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryReference.
func (in *GitHubRepositoryReference) DeepCopy() *GitHubRepositoryReference {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryRuleset) DeepCopyInto(out *GitHubRepositoryRuleset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryRuleset.
func (in *GitHubRepositoryRuleset) DeepCopy() *GitHubRepositoryRuleset {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryRuleset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryRuleset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryRulesetList) DeepCopyInto(out *GitHubRepositoryRulesetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubRepositoryRuleset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryRulesetList.
func (in *GitHubRepositoryRulesetList) DeepCopy() *GitHubRepositoryRulesetList {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryRulesetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryRulesetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryRulesetSpec) DeepCopyInto(out *GitHubRepositoryRulesetSpec) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
	if in.BypassActors != nil {
		in, out := &in.BypassActors, &out.BypassActors
		*out = make([]GitHubRulesetBypassActor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new(GitHubRulesetConditions)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]GitHubRulesetRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryRulesetSpec.
func (in *GitHubRepositoryRulesetSpec) DeepCopy() *GitHubRepositoryRulesetSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryRulesetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryRulesetStatus) DeepCopyInto(out *GitHubRepositoryRulesetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryRulesetStatus.
func (in *GitHubRepositoryRulesetStatus) DeepCopy() *GitHubRepositoryRulesetStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryRulesetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositorySpec) DeepCopyInto(out *GitHubRepositorySpec) {
	*out = *in
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(RepositoryVisibility)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Homepage != nil {
		in, out := &in.Homepage, &out.Homepage
		*out = new(string)
		**out = **in
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(RepositoryFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoInit != nil {
		in, out := &in.AutoInit, &out.AutoInit
		*out = new(bool)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(RepositoryTemplate)
		**out = **in
	}
	if in.DeleteBranchOnMerge != nil {
		in, out := &in.DeleteBranchOnMerge, &out.DeleteBranchOnMerge
		*out = new(bool)
		**out = **in
	}
	if in.VulnerabilityAlerts != nil {
		in, out := &in.VulnerabilityAlerts, &out.VulnerabilityAlerts
		*out = new(bool)
		**out = **in
	}
	if in.IsTemplate != nil {
		in, out := &in.IsTemplate, &out.IsTemplate
		*out = new(bool)
		**out = **in
	}
	if in.MergeOptions != nil {
		in, out := &in.MergeOptions, &out.MergeOptions
		*out = new(RepositoryMergeOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositorySpec.
func (in *GitHubRepositorySpec) DeepCopy() *GitHubRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryStatus) DeepCopyInto(out *GitHubRepositoryStatus) {
	*out = *in
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(RepositoryFeaturesStatus)
		**out = **in
	}
	if in.VulnerabilityAlerts != nil {
		in, out := &in.VulnerabilityAlerts, &out.VulnerabilityAlerts
		*out = new(bool)
		**out = **in
	}
	if in.MergeOptions != nil {
		in, out := &in.MergeOptions, &out.MergeOptions
		*out = new(RepositoryMergeOptionsStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryStatus.
func (in *GitHubRepositoryStatus) DeepCopy() *GitHubRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryTeamAccess) DeepCopyInto(out *GitHubRepositoryTeamAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryTeamAccess.
func (in *GitHubRepositoryTeamAccess) DeepCopy() *GitHubRepositoryTeamAccess {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryTeamAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryTeamAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryTeamAccessList) DeepCopyInto(out *GitHubRepositoryTeamAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubRepositoryTeamAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryTeamAccessList.
func (in *GitHubRepositoryTeamAccessList) DeepCopy() *GitHubRepositoryTeamAccessList {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryTeamAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRepositoryTeamAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryTeamAccessSpec) DeepCopyInto(out *GitHubRepositoryTeamAccessSpec) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryTeamAccessSpec.
func (in *GitHubRepositoryTeamAccessSpec) DeepCopy() *GitHubRepositoryTeamAccessSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryTeamAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRepositoryTeamAccessStatus) DeepCopyInto(out *GitHubRepositoryTeamAccessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRepositoryTeamAccessStatus.
func (in *GitHubRepositoryTeamAccessStatus) DeepCopy() *GitHubRepositoryTeamAccessStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubRepositoryTeamAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRulesetBypassActor) DeepCopyInto(out *GitHubRulesetBypassActor) {
	*out = *in
	if in.ActorID != nil {
		in, out := &in.ActorID, &out.ActorID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRulesetBypassActor.
func (in *GitHubRulesetBypassActor) DeepCopy() *GitHubRulesetBypassActor {
	if in == nil {
		return nil
	}
	out := new(GitHubRulesetBypassActor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRulesetConditions) DeepCopyInto(out *GitHubRulesetConditions) {
	*out = *in
	if in.RefName != nil {
		in, out := &in.RefName, &out.RefName
		*out = new(GitHubRulesetRefNameCondition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRulesetConditions.
func (in *GitHubRulesetConditions) DeepCopy() *GitHubRulesetConditions {
	if in == nil {
		return nil
	}
	out := new(GitHubRulesetConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRulesetRefNameCondition) DeepCopyInto(out *GitHubRulesetRefNameCondition) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRulesetRefNameCondition.
func (in *GitHubRulesetRefNameCondition) DeepCopy() *GitHubRulesetRefNameCondition {
	if in == nil {
		return nil
	}
	out := new(GitHubRulesetRefNameCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRulesetRule) DeepCopyInto(out *GitHubRulesetRule) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRulesetRule.
func (in *GitHubRulesetRule) DeepCopy() *GitHubRulesetRule {
	if in == nil {
		return nil
	}
	out := new(GitHubRulesetRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeam) DeepCopyInto(out *GitHubTeam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeam.
func (in *GitHubTeam) DeepCopy() *GitHubTeam {
	if in == nil {
		return nil
	}
	out := new(GitHubTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubTeam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamList) DeepCopyInto(out *GitHubTeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubTeam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamList.
func (in *GitHubTeamList) DeepCopy() *GitHubTeamList {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubTeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamMembership) DeepCopyInto(out *GitHubTeamMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamMembership.
func (in *GitHubTeamMembership) DeepCopy() *GitHubTeamMembership {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubTeamMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamMembershipList) DeepCopyInto(out *GitHubTeamMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubTeamMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamMembershipList.
func (in *GitHubTeamMembershipList) DeepCopy() *GitHubTeamMembershipList {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubTeamMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamMembershipSpec) DeepCopyInto(out *GitHubTeamMembershipSpec) {
	*out = *in
	out.TeamRef = in.TeamRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamMembershipSpec.
func (in *GitHubTeamMembershipSpec) DeepCopy() *GitHubTeamMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamMembershipStatus) DeepCopyInto(out *GitHubTeamMembershipStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamMembershipStatus.
func (in *GitHubTeamMembershipStatus) DeepCopy() *GitHubTeamMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamMembershipStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamReference) DeepCopyInto(out *GitHubTeamReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamReference.
func (in *GitHubTeamReference) DeepCopy() *GitHubTeamReference {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamSpec) DeepCopyInto(out *GitHubTeamSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Privacy != nil {
		in, out := &in.Privacy, &out.Privacy
		*out = new(GitHubTeamPrivacy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamSpec.
func (in *GitHubTeamSpec) DeepCopy() *GitHubTeamSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubTeamStatus) DeepCopyInto(out *GitHubTeamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubTeamStatus.
func (in *GitHubTeamStatus) DeepCopy() *GitHubTeamStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubTeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretKeyReference) DeepCopyInto(out *LocalSecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretKeyReference.
func (in *LocalSecretKeyReference) DeepCopy() *LocalSecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretKeyReference) DeepCopyInto(out *NamespacedSecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretKeyReference.
func (in *NamespacedSecretKeyReference) DeepCopy() *NamespacedSecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryFeatures) DeepCopyInto(out *RepositoryFeatures) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = new(bool)
		**out = **in
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = new(bool)
		**out = **in
	}
	if in.Wiki != nil {
		in, out := &in.Wiki, &out.Wiki
		*out = new(bool)
		**out = **in
	}
	if in.Discussions != nil {
		in, out := &in.Discussions, &out.Discussions
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryFeatures.
func (in *RepositoryFeatures) DeepCopy() *RepositoryFeatures {
	if in == nil {
		return nil
	}
	out := new(RepositoryFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryFeaturesStatus) DeepCopyInto(out *RepositoryFeaturesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryFeaturesStatus.
func (in *RepositoryFeaturesStatus) DeepCopy() *RepositoryFeaturesStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryFeaturesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMergeOptions) DeepCopyInto(out *RepositoryMergeOptions) {
	*out = *in
	if in.AllowAutoMerge != nil {
		in, out := &in.AllowAutoMerge, &out.AllowAutoMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowMergeCommit != nil {
		in, out := &in.AllowMergeCommit, &out.AllowMergeCommit
		*out = new(bool)
		**out = **in
	}
	if in.AllowRebaseMerge != nil {
		in, out := &in.AllowRebaseMerge, &out.AllowRebaseMerge
		*out = new(bool)
		**out = **in
	}
	if in.AllowSquashMerge != nil {
		in, out := &in.AllowSquashMerge, &out.AllowSquashMerge
		*out = new(bool)
		**out = **in
	}
	if in.MergeCommitTitle != nil {
		in, out := &in.MergeCommitTitle, &out.MergeCommitTitle
		*out = new(RepositoryMergeCommitTitle)
		**out = **in
	}
	if in.MergeCommitMessage != nil {
		in, out := &in.MergeCommitMessage, &out.MergeCommitMessage
		*out = new(RepositoryMergeCommitMessage)
		**out = **in
	}
	if in.SquashMergeCommitTitle != nil {
		in, out := &in.SquashMergeCommitTitle, &out.SquashMergeCommitTitle
		*out = new(RepositorySquashMergeCommitTitle)
		**out = **in
	}
	if in.SquashMergeCommitMessage != nil {
		in, out := &in.SquashMergeCommitMessage, &out.SquashMergeCommitMessage
		*out = new(RepositorySquashMergeCommitMessage)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMergeOptions.
func (in *RepositoryMergeOptions) DeepCopy() *RepositoryMergeOptions {
	if in == nil {
		return nil
	}
	out := new(RepositoryMergeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMergeOptionsStatus) DeepCopyInto(out *RepositoryMergeOptionsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMergeOptionsStatus.
func (in *RepositoryMergeOptionsStatus) DeepCopy() *RepositoryMergeOptionsStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryMergeOptionsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryTemplate) DeepCopyInto(out *RepositoryTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryTemplate.
func (in *RepositoryTemplate) DeepCopy() *RepositoryTemplate {
	if in == nil {
		return nil
	}
	out := new(RepositoryTemplate)
	in.DeepCopyInto(out)
	return out
}
