{{- if and .Values.rbac.create .Values.metrics.enabled .Values.metrics.secure }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-platform-operator.metricsAuthRoleName" . }}
  labels:
    {{- include "github-platform-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-platform-operator.metricsAuthRoleName" . }}
  labels:
    {{- include "github-platform-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "github-platform-operator.metricsAuthRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "github-platform-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- if and .Values.rbac.create .Values.metrics.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-platform-operator.metricsReaderRoleName" . }}
  labels:
    {{- include "github-platform-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}

{{- if and .Values.rbac.create .Values.metrics.enabled .Values.metrics.secure .Values.metrics.serviceMonitor.enabled .Values.metrics.serviceMonitor.prometheusServiceAccount.name .Values.metrics.serviceMonitor.prometheusServiceAccount.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-platform-operator.fullname" . }}-prometheus-metrics
  labels:
    {{- include "github-platform-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "github-platform-operator.metricsReaderRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.metrics.serviceMonitor.prometheusServiceAccount.name }}
    namespace: {{ .Values.metrics.serviceMonitor.prometheusServiceAccount.namespace }}
{{- end }}
