# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/github.k8sready.com_githubproviderconfigs.yaml
- bases/github.k8sready.com_githubrepositories.yaml
- bases/github.k8sready.com_githubrepositoryteamaccesses.yaml
- bases/github.k8sready.com_githubrepositorycollaborators.yaml
- bases/github.k8sready.com_githubenvironments.yaml
- bases/github.k8sready.com_githubactionssecrets.yaml
- bases/github.k8sready.com_githubactionsvariables.yaml
- bases/github.k8sready.com_githubrepositoryrulesets.yaml
# +kubebuilder:scaffold:crdkustomizeresource

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
